#!/usr/bin/env bash

set -euo pipefail

if [ "$UID" -ne 0 ]; then
    echo "must be run as root" >&2
    exit 1
fi

if [ $# -ne 1 ]; then
    echo "usage: $0 <name>" >&2
    exit 1
fi

CLOUD_URL="https://cloud.debian.org/images/cloud/bookworm/latest"
IMAGE_NAME="debian-12-generic-amd64.qcow2"
VM_NAME="$1"
IMAGE_PATH="/var/lib/libvirt/images/$VM_NAME.qcow2"

rm -rf build
mkdir build
cd build

wget "$CLOUD_URL/$IMAGE_NAME"
wget "$CLOUD_URL/SHA512SUMS"

if ! sha512sum --ignore-missing -c SHA512SUMS; then
    echo "download error" >&2
    exit 1
fi

virsh undefine "$VM_NAME" --remove-all-storage || true
qemu-img resize "$IMAGE_NAME" 10G
mv "$IMAGE_NAME" "$IMAGE_PATH"

virsh net-update default add ip-dhcp-host \
  "<host mac='52:54:00:c5:35:6a' name='vpn' ip='192.168.122.254' />" \
  --live --config || true

virt-install \
  --name "$VM_NAME" \
  --vcpus 1 \
  --memory 512 \
  --disk "$IMAGE_PATH,bus=virtio" \
  --cloud-init user-data=../cloud-init.cfg \
  --os-variant debian11 \
  --virt-type kvm \
  --network network=default,model=virtio,mac=52:54:00:c5:35:6a \
  --noautoconsole \
  --video qxl \
  --channel spicevmc \
  --import
